stages:
  - linting
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose

black_check:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config .black .
  
django_tests_check:
  stage: testing
  image: python:3.11
  script:
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py migrate
    - python manage.py test