# Generated by Django 4.2 on 2023-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                ("mail", models.EmailField(max_length=254, verbose_name="почта")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата и время создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "обращение",
                "verbose_name_plural": "обращения",
            },
        ),
    ]
