# Generated by Django 4.2 on 2023-11-06 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0002_feedback_status_statuslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={"verbose_name": "Логи", "verbose_name_plural": "Лог"},
        ),
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(default="пр", max_length=254, verbose_name="имя"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("получено", "получено"),
                    ("в обработке", "в обработке"),
                    ("ответ дан", "ответ дан"),
                ],
                default="получено",
                max_length=15,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                editable=False, max_length=15, verbose_name="статус до"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="время изменения"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to_status",
            field=models.CharField(
                editable=False, max_length=15, verbose_name="статус после"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                editable=False,
                help_text="Пользователь изменивший статус обращения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                related_query_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
