# Generated by Django 4.2 on 2023-11-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_statuslog_options_feedback_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuslog",
            old_name="to_status",
            new_name="to",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(blank=True, max_length=254, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                db_column="from",
                editable=False,
                max_length=15,
                verbose_name="статус до",
            ),
        ),
    ]
