# Generated by Django 4.2 on 2023-11-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0005_feedbackextra_remove_feedback_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="extra",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.feedbackextra",
            ),
            preserve_default=False,
        ),
    ]
