# Generated by Django 4.2 on 2023-11-07 20:41

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_alter_feedback_extra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackextra",
            options={
                "verbose_name": "данные к обращению",
                "verbose_name_plural": "данные к обращениям",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackfiles",
            options={
                "verbose_name": "файлы к обращению",
                "verbose_name_plural": "файлы к обращениям",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="extra",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbackExtra",
                related_query_name="FeedbackExtra",
                to="feedback.feedbackextra",
                verbose_name="доп. данные",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfiles",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                related_query_name="feedback",
                to="feedback.feedback",
                verbose_name="обращение",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfiles",
            name="file",
            field=models.FileField(
                upload_to=feedback.models.FeedbackFiles._feedback_upload_to,
                verbose_name="файл",
            ),
        ),
    ]
