# Generated by Django 4.2 on 2023-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="попытки входа в аккаунт"
            ),
        ),
    ]
