# Generated by Django 4.2 on 2023-11-12 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_options_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="coffe_count",
            new_name="coffee_count",
        ),
    ]
