# Generated by Django 4.2 on 2023-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_attempts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reactivate_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="время отправки ссылки на переактивацию аккаунта",
            ),
        ),
    ]
