# Generated by Django 4.2 on 2023-11-20 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="user_id",
            new_name="user",
        ),
    ]
