# Generated by Django 4.2 on 2023-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0002_rename_item_id_rating_item_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_rating",
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                models.F("user"), models.F("item"), name="unique_rating"
            ),
        ),
    ]
