# Generated by Django 4.2 on 2023-11-20 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0013_alter_item_created_at_alter_item_updated_at"),
        ("rating", "0003_remove_rating_unique_rating_rating_unique_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                related_query_name="rating",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                related_query_name="rating",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
