# Generated by Django 4.2 on 2023-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainimage",
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="catalog/images"),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(upload_to="catalog/main_images"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
