# Generated by Django 4.2 on 2023-10-31 15:24

import catalog.validators
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("catalog", "0006_alter_item_text"),
        (
            "catalog",
            "0007_alter_images_options_alter_category_normalized_name_and_more",
        ),
        ("catalog", "0008_item_is_on_main_alter_category_is_published_and_more"),
        ("catalog", "0009_alter_item_options"),
        ("catalog", "0010_alter_category_normalized_name_alter_images_item_and_more"),
    ]

    dependencies = [
        ("catalog", "0005_alter_images_item_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                validators=[
                    catalog.validators.ValidateMustContain("превосходно", "роскошно")
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AlterModelOptions(
            name="images",
            options={
                "verbose_name": "дополнительное изображение",
                "verbose_name_plural": "дополнительные изображения",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Это нормализованное имя, если вы это видите, значит что то не то)",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Введите только латинские буквы, цифры, знаки подчеркивания или дефис",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Введите число от 1 до 32767",
                validators=[
                    django.core.validators.MaxValueValidator(32767),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                help_text="Загрузите изображения", upload_to="catalog/images"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="item",
            field=models.ForeignKey(
                help_text="Выберете товар",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберете одну категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Выберете главное изображение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="catalog.mainimage",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберете теги.",
                related_name="items",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Описание должно содержать слова `превосходно` или `роскошно`",
                validators=[
                    catalog.validators.ValidateMustContain("превосходно", "роскошно")
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                help_text="загрузите главное изображение",
                upload_to="catalog/main_images",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Это нормализованное имя, если вы это видите, значит что то не то)",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Введите только латинские буквы, цифры, знаки подчеркивания или дефис",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Поставьте галочку, если хотите разместить товар на главной странице",
                verbose_name="на главной",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Поставьте галочку, если хотите опубликовать товар",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название товара. Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Поставьте галочку, если хотите опубликовать товар",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Введите название товара. Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Поставьте галочку, если хотите опубликовать товар",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Введите название товара. Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Это нормализованное имя, если вы это видите, значит что то не то)",
                max_length=150,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="item",
            field=models.ForeignKey(
                help_text="Выберете товар",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберете одну категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Выберете главное изображение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                related_query_name="item",
                to="catalog.mainimage",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберете теги.",
                related_name="items",
                related_query_name="item",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Это нормализованное имя, если вы это видите, значит что то не то)",
                max_length=150,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
