# Generated by Django 4.2 on 2023-10-26 15:24

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_images_item_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                validators=[
                    catalog.validators.ValidateMustContain("превосходно", "роскошно")
                ],
                verbose_name="текст",
            ),
        ),
    ]
