# Generated by Django 4.2 on 2023-10-28 13:29

import catalog.validators
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "verbose_name": "дополнительное изображение",
                "verbose_name_plural": "дополнительные изображения",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Это нормализованное имя, если вы это видите, значит что то не то)",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Введите только латинские буквы, цифры, знаки подчеркивания или дефис",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Введите число от 1 до 32767",
                validators=[
                    django.core.validators.MaxValueValidator(32767),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                help_text="Загрузите изображения", upload_to="catalog/images"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="item",
            field=models.ForeignKey(
                help_text="Выберете товар",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберете одну категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Выберете главное изображение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="catalog.mainimage",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберете теги.",
                related_name="items",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Описание должно содержать слова `превосходно` или `роскошно`",
                validators=[
                    catalog.validators.ValidateMustContain("превосходно", "роскошно")
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                help_text="загрузите главное изображение",
                upload_to="catalog/main_images",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Это нормализованное имя, если вы это видите, значит что то не то)",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Введите только латинские буквы, цифры, знаки подчеркивания или дефис",
                max_length=200,
                verbose_name="слаг",
            ),
        ),
    ]
