# Generated by Django 4.2 on 2023-10-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0007_alter_images_options_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Поставьте галочку, если хотите разместить товар на главной странице",
                verbose_name="на главной",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Поставьте галочку, если хотите опубликовать товар",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название товара. Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Поставьте галочку, если хотите опубликовать товар",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Введите название товара. Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Поставьте галочку, если хотите опубликовать товар",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Введите название товара. Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
