# Generated by Django 4.2 on 2023-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_alter_item_created_at_alter_item_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Это поле создается автоматически",
                null=True,
                verbose_name="дата и время создания",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Это поле создается автоматически",
                null=True,
                verbose_name="дата и время последнего изменения",
            ),
        ),
    ]
